name: 'build-and-deploy'
description: 'Builds the site using Hugo, and deploy it to Firebase Hosting'
inputs:
  firebase-token:
    description: 'Firebase token (obtained via firebase tools -- firebase login:ci)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.firebase-token }}
